### ISSUE TITLE
decrypt doesn't work

### ISSUE THREAD

**Issue by oneofthehorses** [tedgravlin/QR-Crypt#2]
hi! decrypt doesn't work. impossible to choose file\scan qr

**Comment by tedgravlin** [comment]
Hi there! 

QR-Crypt is designed to create a standard QR code that can be scanned with any QR code scanner. You can make a QR code and then scan it with your phone's camera app, or another QR code scanning tool.

I can definitely look into adding a scanner to the website so you can scan codes directly. Let me know if you have any other questions/concerns.

Thanks for the feedback :)

**Comment by oneofthehorses** [comment]
Also proposal: is it possible ask to add second\third secret inside same QR-code? With another passowords ofcourse

Each password answers for own secret. Such an "Plausible deniability"

P.S. maybe this library may help -> https://github.com/sunknudsen/blockcrypt

This project is cool!

Thanks!!

**Comment by tedgravlin** [comment]
That sounds like an interesting idea for sure! Could possibly be something for the future, but no guarantees. This project is more for fun than for high-security applications.

Thanks for the feedback! I'll look into adding a way to scan QR codes on the website.
